name: Setup Bun
description: Setup Bun and install dependencies
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash

